spring.datasource.url=jdbc:mariadb://127.0.0.1:3307/SweetSpot
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

app.jwtSecret=${JWT_SECRET}
app.jwtExpirationMs=86400000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# OAuth2 Client
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com

# 프런트 리다이렉트 목적지 (웹/모바일 별도)
# 프런트(Expo Web)를 Nginx로 https://doitmoney.kro.kr/ 에 올린다는 가정
app.oauth2.redirect.web=http://sweetspot.kro.kr/
app.oauth2.redirect.mobile=sweetspot://oauth/callback
app.oauth2.cookie.secure=false
app.oauth2.cookie.domain=sweetspot.kro.kr

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

# 필요시(네트워크/버전 이슈 회피용) — 없어도 대부분 동작
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
# 비밀번호 재설정 링크가 열릴 프런트 베이스 URL
app.front.base-url=http://sweetspot.kro.kr
# NAVER Maps
naver.maps.base-url=https://maps.apigw.ntruss.com
naver.maps.key-id=${NCP_KEY_ID}
naver.maps.key=${NCP_KEY}