# src/main/resources/application-dev.properties
spring.datasource.url=jdbc:mariadb://hollywood.kro.kr:3307/SweetSpot
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}   # ← 환경변수에서 받음

# JWT
app.jwtSecret=${JWT_SECRET}                 # ← 환경변수에서 받음
app.jwtExpirationMs=86400000

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true